Repository Dayol-Studio/Dayol-iOS, pull requests merged in 2021-03, with the labels that each got.

#67 [Add] Apply EmptyPaper
  Dayol-iOS/TestData/DiaryPageListTestData.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
Labels: Spec, SpecTest

#69 [Add] 1차 속지 데이터 연결
  Dayol-iOS/TestData/DiaryPageTestData.swift
  Dayol-iOS/UI/DiaryPaper/Papers/PaperPresentView.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
Labels: Review Plz, SpecTest

#72 [ADD] 컬렉션 뷰 페이징 구현
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController.swift
Labels: advanced

#74 [MOD] 다이어리 생성 화면에서 엔터 키 삭제 및 글자 수 입력 제한되도록 수정
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationEditableTitle.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
Labels: Review Plz, advanced

#78 [Mod] 다이어리 생성화면 디테일 기능 구현
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationEditableTitle.swift
  Dayol-iOS/UI/Common/DiaryCover/DairyView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
Labels: Review Plz, advanced

#73 [ADD] 다이어리 순서 변경 후 특정 다이어리에 ContentOffset 조절 기능 구현
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController.swift
Labels: advanced

#77 [Mod] 다이어리 커버 뷰의 사이즈 의존성 제거
  Dayol-iOS/Resource/Assets.swift
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/diaryCoverLock.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/diaryCoverLock.imageset/icHomeDiarylock.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/diaryCoverLock.imageset/icHomeDiarylock@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/diaryCoverLock.imageset/icHomeDiarylock@3x.png
  Dayol-iOS/TestData/DiaryListTestData.swift
  Dayol-iOS/UI/Common/DiaryCover/DairyView.swift
  Dayol-iOS/UI/Common/DiaryCover/DiaryCoverView.swift
  Dayol-iOS/UI/Common/DiaryCover/DiaryLockerView.swift
  Dayol-iOS/UI/Common/DiaryCover/DifferentEdgeSettableView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditCoverView.swift
  Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift
  Dayol-iOS/UI/Home/Model/DiaryCoverModel.swift
  Dayol-iOS/UI/Password/View/PasswordTitleView.swift
Labels: Review Plz, advanced

#76 [Enhancement] DiaryPaperViewController, PasswordViewController, StickerView (Ver. UITableView)
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Extension/UIView+Extension.swift
  Dayol-iOS/TestData/DiaryPageTestData.swift
  Dayol-iOS/UI/Common/DYStickerView/DYStickerView.swift
  Dayol-iOS/UI/DiaryPaper/Model/PaperModel.swift
  Dayol-iOS/UI/DiaryPaper/Papers/BasePaper.swift
  Dayol-iOS/UI/DiaryPaper/Papers/CornellPaper.swift
  Dayol-iOS/UI/DiaryPaper/Papers/DailyPaper.swift
  Dayol-iOS/UI/DiaryPaper/Papers/FourPaper.swift
  Dayol-iOS/UI/DiaryPaper/Papers/GridPaper.swift
  Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/View/MonthlyCalendarView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/ViewModel/MonthlyCalendarViewModel.swift
  Dayol-iOS/UI/DiaryPaper/Papers/MujiPaper.swift
  Dayol-iOS/UI/DiaryPaper/Papers/PaperPresentView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/PaperPresenterView/DrawingContentView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/PaperPresenterView/PaperPresentView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/PaperPresenterView/StickerContentView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/PaperProvider.swift
  Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/View/WeeklyCalendarView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/ViewModel/WeeklyCalendarViewModel.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewerViewController.swift
  Dayol-iOS/UI/Password/View/PasswordButton.swift
  Dayol-iOS/UI/Password/View/PasswordDisplayedView.swift
  Dayol-iOS/UI/Password/View/PasswordTitleView.swift
  Dayol-iOS/UI/Password/View/PasswordViewController.swift
  Dayol-iOS/UI/Password/ViewModel/PasswordViewModel.swift
  Dayol-iOS/Util/DeviceInfo.swift
Labels: Spec, advanced

#79 [Add] 다이어리 생성 화면 지우개 설정 뷰 추가
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Extension/UIColor+Extension.swift
  Dayol-iOS/Localization/en.lproj/Localizable.strings
  Dayol-iOS/Localization/ko.lproj/Localizable.strings
  Dayol-iOS/Resource/Assets.swift
  Dayol-iOS/Resource/Common.xcassets/Modal/Contents.json
  Dayol-iOS/Resource/Common.xcassets/Modal/btnModaldown.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/Modal/btnModaldown.imageset/btnModaldown.png
  Dayol-iOS/Resource/Common.xcassets/Modal/btnModaldown.imageset/btnModaldown@2x.png
  Dayol-iOS/Resource/Common.xcassets/Modal/btnModaldown.imageset/btnModaldown@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_info.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_info.imageset/icInfo.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_info.imageset/icInfo@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_info.imageset/icInfo@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large.imageset/imgEraser3.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large.imageset/imgEraser3@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large.imageset/imgEraser3@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large_select.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large_select.imageset/imgEraser3Select.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large_select.imageset/imgEraser3Select@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_large_select.imageset/imgEraser3Select@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium.imageset/imgEraser2.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium.imageset/imgEraser2@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium.imageset/imgEraser2@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium_select.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium_select.imageset/imgEraser2Select.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium_select.imageset/imgEraser2Select@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_medium_select.imageset/imgEraser2Select@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small.imageset/imgEraser1.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small.imageset/imgEraser1@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small.imageset/imgEraser1@3x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small_select.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small_select.imageset/imgEraser1Select.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small_select.imageset/imgEraser1Select@2x.png
  Dayol-iOS/Resource/Common.xcassets/ToolBarContent/toolBar_small_select.imageset/imgEraser1Select@3x.png
  Dayol-iOS/UI/Common/DYModalViewController/DYModalViewController.swift
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationDrawingToolbar.swift
  Dayol-iOS/UI/Common/View/ToolBarContent/EraseOptionButton.swift
  Dayol-iOS/UI/Common/View/ToolBarContent/EraseSettingView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController+ToolBar.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
Labels: Review Plz, Spec
