Repository Dayol-Studio/Dayol-iOS, pull requests merged in 2021-01, with the labels that each got.

#12 [Add] DiaryView, HomeView, PasswordView Integration
  Dayol-iOS/UI/Common/DiaryCover/DairyView.swift
  Dayol-iOS/UI/Common/DiaryCover/DiaryCoverView.swift
  Dayol-iOS/UI/Common/DiaryCover/DiaryLockerView.swift
  Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/UI/Home/Main/ViewController/HomeViewController.swift
  Dayol-iOS/UI/Password/View/PasswordTitleView.swift
  Dayol-iOS/UI/Password/View/PasswordViewController+Bind.swift
  Dayol-iOS/UI/Password/View/PasswordViewController.swift
Labels: Review Plz, Spec

#21 [Add] 다이어리 리스트 순서 변경 기능 추가
  Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController.swift
Labels: Review Plz, Spec

#25 [Add] 다욜 앱 아이콘 추가
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120-1.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40-1.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40-2.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58-1.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80-1.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Dayol-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Spec

#27 [Pod] Add FsCalendar 2.8.2
  Podfile
Labels: setting

#26 [Add] Diary Edit View (ViewOnly)
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Extension/UIFont+Extension.swift
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/colorSelect.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/colorSelect.imageset/btnColorSelect.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/colorSelect.imageset/btnColorSelect@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/colorSelect.imageset/btnColorSelect@3x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/dayolCoverLogo.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/dayolCoverLogo.imageset/imgDayolMark.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/dayolCoverLogo.imageset/imgDayolMark@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryEdit/dayolCoverLogo.imageset/imgDayolMark@3x.png
  Dayol-iOS/UI/Common/DiaryCover/DairyView.swift
  Dayol-iOS/UI/Common/DiaryCover/DiaryCoverColor.swift
  Dayol-iOS/UI/Common/DiaryCover/DiaryCoverView.swift
  Dayol-iOS/UI/DiaryEdit/DiaryEditViewController.swift
  Dayol-iOS/UI/DiaryEdit/View/Cell/DiaryEditColorPaletteCell.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditColorPaletteView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditCoverView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditToggleView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
  Dayol-iOS/UI/Home/DiaryList/ViewModel/DiaryListViewModel.swift
  Dayol-iOS/UI/Home/Main/ViewController/HomeViewController.swift
  Dayol-iOS/UI/Home/Model/DiaryCoverModel.swift
  Dayol-iOS/UI/Password/View/PasswordViewController.swift
Labels: Review Plz, Spec

#28 [Add] DYCustomViewController, DYModalConfiguration
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/UI/Common/DYModalViewController/DYModalConfiguration.swift
  Dayol-iOS/UI/Common/DYModalViewController/DYModalViewController.swift
Labels: Review Plz, Spec

#29 [Add] DiaryPaperVC, DiaryEmptyPageView
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Resource/Common.xcassets/DiaryPaper/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryPaper/diaryAdd.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryPaper/diaryAdd.imageset/icDiaryAdd.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaper/diaryAdd.imageset/icDiaryAdd@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaper/diaryAdd.imageset/icDiaryAdd@3x.png
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationController.swift
  Dayol-iOS/UI/DiaryPaper/View/DiaryPaperEmptyView.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperListViewController.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/Util/DeviceInfo.swift
Labels: Review Plz, Spec

#36 [Add] System Photo Picker 기능 추가
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController+PhotoPicker.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
Labels: Review Plz, Spec

#40 [Add] 무지, 그리드, 데일리 속지 View 구현
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Extension/UIFont+Extension.swift
  Dayol-iOS/UI/DiaryPaper/Model/PaperModel.swift
  Dayol-iOS/UI/DiaryPaper/Papers/BasePaperView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/DailyPaperView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/GridPaperView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/MujiPaperView.swift
  Dayol-iOS/UI/DiaryPaper/ViewModel/PaperViewModel.swift
Labels: Review Plz, Spec

#48 [Add] DYToast 정의
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Extension/UIView+Extension.swift
  Dayol-iOS/UI/Common/Toast/DYToastView.swift
Labels: Review Plz, Spec
