Repository Dayol-Studio/Dayol-iOS, pull requests merged in 2021-02, with the labels that each got.

#42 [Add] DYKeybordInputAccessoryView
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/Contents.json
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_bullet.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_bullet.imageset/btnBullet.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_bullet.imageset/btnBullet@2x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_bullet.imageset/btnBullet@3x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_checkbox.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_checkbox.imageset/btnCheckbox.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_checkbox.imageset/btnCheckbox@2x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_checkbox.imageset/btnCheckbox@3x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_keyboarddown.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_keyboarddown.imageset/icKeyboardDown.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_keyboarddown.imageset/icKeyboardDown@2x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_keyboarddown.imageset/icKeyboardDown@3x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_textstyle.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_textstyle.imageset/btnTextstyle.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_textstyle.imageset/btnTextstyle@2x.png
  Dayol-iOS/Resource/Common.xcassets/KeybordInputAccessory/keyboard_accessory_textstyle.imageset/btnTextstyle@3x.png
  Dayol-iOS/UI/DiaryPaper/InputAccessaryView/DYKeybordInputAccessoryView.swift
Labels: Review Plz, Spec

#50 [Add] 다이어리의 전체 페이지 수정 모달 뷰 구현
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Localization/en.lproj/Localizable.strings
  Dayol-iOS/Localization/ko.lproj/Localizable.strings
  Dayol-iOS/Resource/Assets.swift
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_add_paper.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_add_paper.imageset/imgAddPage.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_add_paper.imageset/imgAddPage@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_add_paper.imageset/imgAddPage@3x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_starred.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_starred.imageset/btnDiaryFavoriteOn.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_starred.imageset/btnDiaryFavoriteOn@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_cell_starred.imageset/btnDiaryFavoriteOn@3x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_chevron_down.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_chevron_down.imageset/btnMemoDetailCopy4.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_chevron_down.imageset/btnMemoDetailCopy4@2x.png
  Dayol-iOS/Resource/Common.xcassets/DiaryPaperList/paper_list_chevron_down.imageset/btnMemoDetailCopy4@3x.png
  Dayol-iOS/Resource/Common.xcassets/InfoView/Contents.json
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Close.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Close.imageset/btnInfoX.png
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Close.imageset/btnInfoX@2x.png
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Close.imageset/btnInfoX@3x.png
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Info.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Info.imageset/icInfo.png
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Info.imageset/icInfo@2x.png
  Dayol-iOS/Resource/Common.xcassets/InfoView/InfoView_Icon_Info.imageset/icInfo@3x.png
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/downwardArrowButton.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/downwardArrowButton.imageset/btnModaldown.png
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/downwardArrowButton.imageset/btnModaldown@2x.png
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/downwardArrowButton.imageset/btnModaldown@3x.png
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationItemCreator.swift
  Dayol-iOS/UI/Common/View/InfoView.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperListViewController.swift
  Dayol-iOS/UI/DiaryPaperAdd/ViewController/AddPaperViewController.swift
  Dayol-iOS/UI/DiaryPaperModal/Model/AddPaperModel.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperAdd/View/AddPaperCell.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperAdd/View/AddPaperContentView+UICollectionView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperAdd/View/AddPaperContentView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperAdd/View/AddPaperHeaderReusableView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperAdd/View/AddPaperHeaderView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperAdd/ViewModel/AddPaperContentViewModel.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListAddCell.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListCell.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListContentView+CollectionView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListContentView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListHeaderView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/ViewModel/PaperListContentViewModel.swift
  Dayol-iOS/UI/DiaryPaperModal/ViewController/PaperModalViewController.swift
Labels: Review Plz, Spec

#49 [Add] Weekly Calendar View
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/View/MonthlyCalendarCollectionView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/View/MonthlyCalendarView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/View/Cell/WeeklyCalendarViewCell.swift
  Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/View/WeeklyCalendarHeaderView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/View/WeeklyCalendarView.swift
  Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/ViewModel/WeeklyCalendarViewModel.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperListViewController.swift
Labels: Review Plz, Spec

#53 [Add] SettingDetailViewController 구현
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Localization/en.lproj/Localizable.strings
  Dayol-iOS/Localization/ko.lproj/Localizable.strings
  Dayol-iOS/UI/Settings/Model/SettingsModel.swift
  Dayol-iOS/UI/Settings/ViewController/SettingsDetailViewController.swift
  Dayol-iOS/UI/Settings/ViewController/SettingsViewController.swift
  Dayol-iOS/UI/Settings/ViewModel/SettingsViewModel.swift
Labels: Review Plz, Spec

#58 [Mod] Setting화면 진입 시 패드일 경우 컨텐츠 사이즈를 가이드에 맞게 수정
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+bind.swift
Labels: Review Plz, Spec

#59 [Add] 가로, 세로 줄이 있는 속지 구현
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/UI/DiaryPaper/Papers/FourPaper.swift
Labels: Review Plz, Spec

#54 [Add] Scenario For Setting Password
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/TestData/DiaryListTestData.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
  Dayol-iOS/UI/Home/Model/DiaryCoverModel.swift
  Dayol-iOS/UI/Password/View/PasswordTitleView.swift
  Dayol-iOS/UI/Password/View/PasswordViewController+Bind.swift
  Dayol-iOS/UI/Password/View/PasswordViewController.swift
  Dayol-iOS/UI/Password/ViewModel/PasswordViewModel.swift
Labels: Review Plz, Spec, SpecTest

#57 [Add] 설정 2뎁스 페이지 중 휴지통 설정 페이지 구현
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Extension/CALayer+Extension.swift
  Dayol-iOS/TestData/DeletedPageListTestData.swift
  Dayol-iOS/UI/DiaryPaper/Model/PaperModel.swift
  Dayol-iOS/UI/Settings/Model/SettingsModel.swift
  Dayol-iOS/UI/Settings/View/DetailSettings/DeletedPageCell.swift
  Dayol-iOS/UI/Settings/View/DetailSettings/DeletedPageListView.swift
  Dayol-iOS/UI/Settings/ViewController/DetailSettingsViewController.swift
  Dayol-iOS/UI/Settings/ViewController/SettingsDetailViewController.swift
  Dayol-iOS/UI/Settings/ViewController/SettingsViewController.swift
  Dayol-iOS/UI/Settings/ViewModel/DetailSettings/DeletedPageViewModel.swift
Labels: Review Plz, Spec

#55 [Add] Scenario For Check Password
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditColorPaletteView.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+bind.swift
  Dayol-iOS/UI/Password/View/PasswordViewController.swift
  Dayol-iOS/UI/Password/ViewModel/PasswordViewModel.swift
Labels: Review Plz, Spec, SpecTest

#60 [#56][Mod] localization 파일 수정
  Dayol-iOS/Localization/en.lproj/Localizable.strings
  Dayol-iOS/Localization/ko.lproj/Localizable.strings
Labels: Review Plz, Spec

#61 [Add] Create PaperModel Data For Test
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/TestData/DiaryPageListTestData.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
Labels: Review Plz

#62 [Add] Apply Spec of DiaryPapers Title
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/backButtonWhite.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/backButtonWhite.imageset/btnBackWhite.png
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/backButtonWhite.imageset/btnBackWhite@2x.png
  Dayol-iOS/Resource/Common.xcassets/Navigation/Bar/backButtonWhite.imageset/btnBackWhite@3x.png
  Dayol-iOS/TestData/DiaryListTestData.swift
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationController.swift
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationEditableTitle.swift
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationItemCreator.swift
  Dayol-iOS/UI/Common/DYNavigationController/DYNavigationTitle.swift
  Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
  Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift
  Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+bind.swift
  Dayol-iOS/UI/Home/Model/DiaryCoverModel.swift
Labels: Spec

#63 [Add] 설정 2뎁스 페이지 중 백업 설정 페이지 구현
  Dayol-iOS.xcodeproj/project.pbxproj
  Dayol-iOS/Localization/en.lproj/Localizable.strings
  Dayol-iOS/Localization/ko.lproj/Localizable.strings
  Dayol-iOS/Resource/Assets.swift
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_info.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_info.imageset/icInfo.png
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_info.imageset/icInfo@2x.png
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_info.imageset/icInfo@3x.png
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_next.imageset/Contents.json
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_next.imageset/icSettingNext.png
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_next.imageset/icSettingNext@2x.png
  Dayol-iOS/Resource/Common.xcassets/Setting/settings_backup_next.imageset/icSettingNext@3x.png
  Dayol-iOS/UI/Settings/View/DataBackup/DataBackupCloudContentView.swift
  Dayol-iOS/UI/Settings/View/DataBackup/DataBackupExportContentView.swift
  Dayol-iOS/UI/Settings/View/DataBackup/DataBackupView.swift
  Dayol-iOS/UI/Settings/View/DeletedPageList/DeletedPageCell.swift
  Dayol-iOS/UI/Settings/View/DeletedPageList/DeletedPageListView.swift
  Dayol-iOS/UI/Settings/ViewController/DetailSettingsViewController.swift
  Dayol-iOS/UI/Settings/ViewModel/DataBackupViewModel.swift
  Dayol-iOS/UI/Settings/ViewModel/DeletedPageViewModel.swift
Labels: Review Plz, Spec

#65 [Add] Apply Diary Paper List Test Data
  Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListContentView.swift
  Dayol-iOS/UI/DiaryPaperModal/PaperList/ViewModel/PaperListContentViewModel.swift
  Dayol-iOS/UI/DiaryPaperModal/ViewController/PaperModalViewController.swift
Labels: Review Plz, Spec, SpecTest
